add_newline = true

format = """
$os\
$directory\
[î‚¼](fg:#89b4fa bg:#1e1e2e)\
$git_branch\
$git_status\
[î‚°](fg:#1e1e2e)\
$fill\
[î‚²](fg:#1e1e2e)\
$cmd_duration\
$time\
\n$character\
"""

[character]
error_symbol = " [â””â”€Â»](bold red)"
success_symbol = " [â””â”€Â»](bold #fab387)"

[os]
format = "[ $symbol]($style)"
disabled = false
style = "bg:#313244 fg:#89b4fa"

[os.symbols]
Windows = "î˜ª "
Macos = "ï…¹ "
Ubuntu = "ó°•ˆ "

[directory]
format = '[ $path]($style)[$read_only]($read_only_style)'
read_only = "î¬‘ "
read_only_style = 'fg:#f38ba8 bg:#1e1e2e'
truncation_length = 100
truncation_symbol = ""
truncate_to_repo = true
style = 'bg:#89b4fa fg:#a6e3a1'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = " ï„“ îœ¥ "
truncation_symbol = ''
style = 'fg:#89b4fa bg:#1e1e2e'

[git_status]
conflicted = "ğŸ’¥"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸŒšâ€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = 'ğŸ”¦'
renamed = "ğŸ·"
deleted = "ğŸ—‘"
style = 'fg:#f9e2af bg:#1e1e2e'
up_to_date = 'âœ“'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#a6e3a1 bg:#1e1e2e'
deleted_style = 'fg:#f38ba8 bg:#1e1e2e'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[cmd_duration]
disabled = false
min_time = 1
style = 'fg:#fab387 bg:#1e1e2e'
format = "[î‚ $duration]($style)"

[container]
format = '[$symbol \[$name\]]($style) '

[time]
disabled = false
format = "[ î‚³ ï€— $time ]($style)"
time_format = '%H:%M'
style = 'bg:#1e1e2e fg:#cdd6f4'

[fill]
symbol = 'â”€'
style = '#585b70'
